apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bookinfo-reviews
  namespace: bookinfo
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      # Revision名の指定
      name: bookinfo-reviews-v2
      labels:
        app: reviews
        version: v2
    spec:
      containers:
        - image: keitamochizuki/bookinfo-reviews-v2:v1.9.0
          env:
            - name: SERVICES_DOMAIN
              value: "bookinfo.svc.cluster.local"
            - name: RATINGS_HOSTNAME
              value: "bookinfo-ratings"
            - name: RATINGS_PORT
              value: "80"
            # ratingへのタイムアウト値設定(ms)
            - name: TIMEOUT
              value: "60000"

          # コンテナのポート指定
          ports:
            - containerPort: 9080
  traffic:
  - percent: 0
    revisionName: bookinfo-reviews-v1
    tag: v1
  - percent: 100
    revisionName: bookinfo-reviews-v2
    tag: v2